name:                haskell-toy-broker
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- nonempty-containers
- async
- mtl
- optparse-applicative
- optparse-generic
- aeson
- neat-interpolation
- stm
- concurrency
- dejafu

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-packages

library:
  source-dirs: src

executables:
  haskell-toy-broker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-toy-broker

tests:
  haskell-toy-broker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-toy-broker
    - hspec
    - hspec-discover
    - QuickCheck
    - hunit-dejafu

verbatim:
  cabal-version: 3.0
